
#Configuration for Sonata User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    SonataUserBundle: ~

sonata_user:
  admin:                  # Admin Classes
      user:
          class:          Sonata\UserBundle\Admin\Entity\UserAdmin
          controller:     SonataAdminBundle:CRUD
          translation:    SonataUserBundle

      group:
          class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
          controller:     SonataAdminBundle:CRUD
          translation:    SonataUserBundle
